### ISSUE TITLE
Validate existence before any assignment

### ISSUE THREAD

**Issue by laamzarescu** [muhammadatt/short-url#11]
https://github.com/muhammadatt/short-url/blob/93810b539723fa7309db0ba1d31a9dfd7a5d689a/app/Http/Controllers/ApiController.php#L23

You should validate the existence of all your request parameters before fill any model.
Anyone can easily send a request through Postman/Burp Suite/or any others soft without sending the actual schema.

**Comment by muhammadatt** [comment]
I'm currently handling this the "Laravel way", by setting a $fillable property inside the Url model which defines which properties will be accepting when executing the fill command:

protected $fillable = ['original', 'nsfw'];
